<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__button-1 new-address-next-step-button</name>
   <tag></tag>
   <elementGuidId>ccab1152-512d-4231-b6eb-c62d607a7f26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#shipping-buttons-container > input.button-1.new-address-next-step-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value='Continue'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>40b57c13-a24f-4e30-a792-9b172105dcf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>96474691-952b-4da2-a6f2-f368c30ecfc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-1 new-address-next-step-button</value>
      <webElementGuid>9935063d-dc4f-4cce-b99d-334c83d8a9d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>28f61e7a-38f0-47c2-be61-9ef2e60fc497</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>Shipping.save()</value>
      <webElementGuid>ecc2ca6b-3e76-4aee-a938-43e4f2f165a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>31c4cf8a-81a5-4d28-b542-d9a49f303e8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shipping-buttons-container&quot;)/input[@class=&quot;button-1 new-address-next-step-button&quot;]</value>
      <webElementGuid>f50a207b-49c4-4f0d-9ba3-1b8e9aeabbaf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value='Continue'])[2]</value>
      <webElementGuid>51010770-15fb-4b51-b4c8-a2b21ae64e46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shipping-buttons-container']/input</value>
      <webElementGuid>532bfc70-2e55-4ca1-9d46-63c06b792c9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div[2]/div/input</value>
      <webElementGuid>d00365b9-159c-4da4-a9fb-26126fb965aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @title = 'Continue']</value>
      <webElementGuid>3234dcd3-e95a-41b9-b741-91a546605de3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
