<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Fax number_PickUpInStore</name>
   <tag></tag>
   <elementGuidId>365c9b54-3afe-4371-9920-13c85b826fd8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PickUpInStore</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PickUpInStore']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d3e8a341-2324-404c-9e31-9c6d2934259d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PickUpInStore</value>
      <webElementGuid>eebbb803-eb8b-4d3e-9eff-268821a3132c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PickUpInStore</value>
      <webElementGuid>f2f87002-dfaf-4bde-a8c2-619a687b22eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>Shipping.togglePickUpInStore(this)</value>
      <webElementGuid>1b5957bf-2823-47c2-b68b-4f6879a7cd94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>eb7871ee-c828-4c95-859e-de92396153d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c361773b-568b-49d8-9499-aab199349510</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PickUpInStore&quot;)</value>
      <webElementGuid>065c66c3-64ec-4802-89a4-4e9f2505f6e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PickUpInStore']</value>
      <webElementGuid>258de623-fd0f-4d07-a13c-6bf815072d75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkout-shipping-load']/div/div[2]/p/input</value>
      <webElementGuid>4a5e9962-ed99-4814-baee-5fa155a6aac9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/input</value>
      <webElementGuid>86dcb4cf-0f0a-4fd5-b17a-6db340132274</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'PickUpInStore' and @name = 'PickUpInStore' and @type = 'checkbox']</value>
      <webElementGuid>7e75d802-212a-4200-8837-df095abec30b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
