<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_The one day air shipping_shippingoption</name>
   <tag></tag>
   <elementGuidId>0b5fdeb8-ca77-427b-81e2-ae5e41830efd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#shippingoption_2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='shippingoption_2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>678929bd-f46f-4eac-bcdb-722a3f8519ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>shippingoption_2</value>
      <webElementGuid>5047e57e-4c0a-4bf8-9441-35f5f2755864</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>2299bb68-37a0-4c64-9e3c-e09ae6203974</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>shippingoption</value>
      <webElementGuid>8f7bd297-7d78-4493-97da-d326ee168841</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2nd Day Air___Shipping.FixedRate</value>
      <webElementGuid>95470eb3-7e49-4c0f-ac2d-bb8f1a2e71ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shippingoption_2&quot;)</value>
      <webElementGuid>9bc33985-4792-4b3a-8e6f-4f3c8a0d169a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='shippingoption_2']</value>
      <webElementGuid>d1bf9cbf-09af-4545-8f29-74b73a2388a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkout-shipping-method-load']/div/div/ul/li[3]/div/input</value>
      <webElementGuid>f2b9131a-4835-479b-bcf6-7c464bcb347a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/input</value>
      <webElementGuid>507f7a35-3cd8-4575-b61b-f58b1e9e6e91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'shippingoption_2' and @type = 'radio' and @name = 'shippingoption']</value>
      <webElementGuid>8a8ce3af-6fea-4ec1-9c77-c7cc6be68a24</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
