<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Ground (0.00)_shippingoption</name>
   <tag></tag>
   <elementGuidId>11d54b39-9fc7-4728-b925-61ff892d55f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#shippingoption_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='shippingoption_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b6ab6989-eb5d-4005-bf5c-7bcf504c136f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>shippingoption_1</value>
      <webElementGuid>a9e1c090-1314-4887-8208-b4711d702add</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>379bcc3f-e1a7-48e5-ad84-8ad9ca914768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>shippingoption</value>
      <webElementGuid>c26de202-8629-4c4f-a16b-186cf35d6b89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Next Day Air___Shipping.FixedRate</value>
      <webElementGuid>63144107-8762-4f8d-b7b1-555736263c05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shippingoption_1&quot;)</value>
      <webElementGuid>6083e2ac-9292-46f6-a5b0-099afa26fc9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='shippingoption_1']</value>
      <webElementGuid>1b6dd08e-7394-4a48-a007-2113d2e97cdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkout-shipping-method-load']/div/div/ul/li[2]/div/input</value>
      <webElementGuid>4867561d-3b58-4dfd-93d8-4627199fdd1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/input</value>
      <webElementGuid>87d38343-664c-41be-af4c-25428706fb95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'shippingoption_1' and @type = 'radio' and @name = 'shippingoption']</value>
      <webElementGuid>8ae51e1b-2d62-4730-81fb-4aa824cc9249</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
