<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Check  Money Order (5.00)_paymentmethod</name>
   <tag></tag>
   <elementGuidId>b3e08b5c-5b9f-4aed-b448-243bcc6555b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#paymentmethod_2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='paymentmethod_2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f881c3f3-ae77-4519-be6e-3c427681757c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>paymentmethod_2</value>
      <webElementGuid>8ef9fc63-d255-4319-8e11-5804451796e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>c9c8d4f1-42ea-4a6b-8e4c-e520a0b1a7af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>paymentmethod</value>
      <webElementGuid>a30d4130-fd42-496d-b3df-72fe0f7abce0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Payments.Manual</value>
      <webElementGuid>a72e3cb7-0847-46a7-8a19-525ada4c05b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
      <webElementGuid>65914b85-e106-4440-9e0e-9fa7677b9be3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paymentmethod_2&quot;)</value>
      <webElementGuid>95b5792d-e50c-4f20-8ea0-4e98bd0e0933</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='paymentmethod_2']</value>
      <webElementGuid>e11e1b59-eda2-427d-b8ae-c01fc9ddf623</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkout-payment-method-load']/div/div/ul/li[3]/div/div[2]/input</value>
      <webElementGuid>98fbf853-40f9-4bd5-b94a-f5d10e7d7735</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/div[2]/input</value>
      <webElementGuid>4a832ef6-1cee-4c12-9a70-fe4b3bf576e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'paymentmethod_2' and @type = 'radio' and @name = 'paymentmethod' and @checked = 'checked']</value>
      <webElementGuid>6278fe69-b588-45b6-bf98-2af936a125b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
