<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Address 1_BillingNewAddress.Address1</name>
   <tag></tag>
   <elementGuidId>8c03604f-00ef-4ae8-a7e3-16334d901694</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#BillingNewAddress_Address1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='BillingNewAddress_Address1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3ba0d121-7bbb-4d60-8462-3083fe0d1ed6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-box single-line</value>
      <webElementGuid>b6b24240-1b46-497b-a4d5-865bc44d7de4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ecce14f2-fcd5-4160-bb2d-a8e201fa3447</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Street address is required</value>
      <webElementGuid>be34178b-6f08-4f2f-8275-59259dc8a99e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BillingNewAddress_Address1</value>
      <webElementGuid>edc5f0d8-1878-4d74-a017-dea4acdecb27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BillingNewAddress.Address1</value>
      <webElementGuid>3754f082-59ad-4f06-b495-73f7aad65132</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>af13f78b-7160-4ffb-a54f-bce0c0b630a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BillingNewAddress_Address1&quot;)</value>
      <webElementGuid>973a6ac8-0398-431b-9c20-e8684388b2df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='BillingNewAddress_Address1']</value>
      <webElementGuid>d3768e34-c87a-4c32-9f3d-e0a3af7bc15b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='billing-new-address-form']/div/div/div/div[8]/input</value>
      <webElementGuid>fbe126b3-9b73-4196-ae33-1e2bfe9842a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/input</value>
      <webElementGuid>ac53c0d3-3de1-43db-95f3-46f5346d5fdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'BillingNewAddress_Address1' and @name = 'BillingNewAddress.Address1' and @type = 'text']</value>
      <webElementGuid>dccba5ed-3b59-4869-9c69-97ee89738d91</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
