<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Zip  postal code_BillingNewAddress.Zi_77bd94</name>
   <tag></tag>
   <elementGuidId>ca6d8815-ec77-4644-86d9-0c984e212121</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#BillingNewAddress_ZipPostalCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='BillingNewAddress_ZipPostalCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2f0c5987-825f-4fb5-bad3-a80b976bfef1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-box single-line</value>
      <webElementGuid>6f3c5697-ea09-40d1-9162-97259d66144b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6084421c-c7a3-4fe9-b23d-9fe705f3de08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Zip / postal code is required</value>
      <webElementGuid>97303686-f499-4cde-9a02-64c274056a60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BillingNewAddress_ZipPostalCode</value>
      <webElementGuid>020b6c31-f33b-458f-b595-9438d525847a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BillingNewAddress.ZipPostalCode</value>
      <webElementGuid>4a75c8ce-1e4f-42b5-831b-195d1a64f3df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e496b932-d1a3-4ebd-a4aa-663d38fe2640</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BillingNewAddress_ZipPostalCode&quot;)</value>
      <webElementGuid>8acaf770-c11d-48c0-a921-8d7a7bef8dca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='BillingNewAddress_ZipPostalCode']</value>
      <webElementGuid>452b37b1-d85e-41fc-9e64-41ed6a549a7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='billing-new-address-form']/div/div/div/div[10]/input</value>
      <webElementGuid>6206ef91-7350-4fbc-acbe-56138608930d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/input</value>
      <webElementGuid>8b6916f8-c5de-40ac-b738-3c6d877d39f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'BillingNewAddress_ZipPostalCode' and @name = 'BillingNewAddress.ZipPostalCode' and @type = 'text']</value>
      <webElementGuid>3ec2287a-9905-4836-94b2-435794edfb35</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
