<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Card number_CardNumber</name>
   <tag></tag>
   <elementGuidId>e3e0b4d5-c18f-4c07-a46d-3d2e51ce9c0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CardNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CardNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6d63f24b-bd70-4f24-b801-75f7dd7a992b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>9922a159-d9ea-40bd-8f69-1163f2cda91b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CardNumber</value>
      <webElementGuid>c9342e9d-7217-4e4a-8b97-433b9ecbbe31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>22</value>
      <webElementGuid>43b70fbf-eaf3-4cc0-aa25-afa9b737c147</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CardNumber</value>
      <webElementGuid>1d6178c5-aa16-4add-b4b9-abbce919c3b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>12ac96ba-7815-4a3f-a964-5b53e24e331b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CardNumber&quot;)</value>
      <webElementGuid>7ba0028a-5fa8-4857-95d8-c8a680db3322</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CardNumber']</value>
      <webElementGuid>7afe87e7-7809-4107-95a6-4ea688cca08f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkout-payment-info-load']/div/div/div/table/tbody/tr[3]/td[2]/input</value>
      <webElementGuid>af5d3d62-f684-4587-938d-a31e582859b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/input</value>
      <webElementGuid>791e457a-a7b7-4b55-bbc7-29d97eb76f56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'CardNumber' and @name = 'CardNumber' and @type = 'text']</value>
      <webElementGuid>9c138fdc-d7a9-496d-a985-db36b4a826fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
