<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cardholder name_CardholderName</name>
   <tag></tag>
   <elementGuidId>38282e2b-e845-4cbe-b4d9-4455bd069736</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CardholderName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CardholderName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ef49730d-95a4-40a9-abe7-7523c76633a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2a2b5fe8-f5ab-4040-9910-50f8957534c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CardholderName</value>
      <webElementGuid>f97f9117-4415-4f19-935c-a872833c9bf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CardholderName</value>
      <webElementGuid>b91a9874-8404-49dc-a500-d2d3b3155de8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>209726d0-9eea-459c-90eb-ef83e45a07e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CardholderName&quot;)</value>
      <webElementGuid>26fac677-e9b4-4aaf-9429-b26f934deb2f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CardholderName']</value>
      <webElementGuid>cac24e49-535f-435e-9031-1480d99cdc2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkout-payment-info-load']/div/div/div/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>de8fd256-e3d2-4304-82b3-7519ead105eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>51888489-e1f5-4cec-ad92-1a8576d86211</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'CardholderName' and @name = 'CardholderName' and @type = 'text']</value>
      <webElementGuid>c7d17135-deb1-4d41-8bae-caf20ef33184</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
